import { KeyboardEvent, useState } from 'react';

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

type Data = {
  name: string,
  icon: string,
  main: string
}

const Home = () => {

  const [cities, setCities] = useState(Array<Data>)
  const [isLoading, setLoading] = useState(false)

  const handleKeyDown = async(event: KeyboardEvent) => {
    if (event.key === 'Enter') {
      const { value } = event.target as HTMLTextAreaElement
      
      setLoading(true)
      const data = await getWeather(value)
      setCities(data)
      setLoading(false)
    }
  }

  const getWeather = async (zip: string) => {
    const res  = await fetch('api/weather/', {
      method: 'POST',
      body: zip,
    })
    const data = await res.json()
    
    return data
  }

  // list weather by cities
  let listCities = <span className={styles.card}>NO DATA</span>
  if (cities.length) {
    listCities = <>{cities.map((city, i) =>
      <span className={styles.card} key={i}>
        <label>{city.name}</label>
        <Image
          src={city.icon}
          alt={city.main}
          width={40}
          height={40}
        />
      </span>
    )}</>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Weather Forecast</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Weather <span>Forecast</span>
        </h1>

        <p className={styles.description}>
          <input
            className={styles.zip}
            type="text"
            name='zip'
            placeholder='Enter zip code'
            maxLength={5}
            onKeyDown={handleKeyDown}
          />
        </p>

        <div className={styles.grid}>
          {isLoading ? 'Feeling the weather...' : listCities}     
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home